export enum ErrorCode {
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  PLACE_CATEGORY_DUPLICATE = 'PLACE_CATEGORY_DUPLICATE',
  PLACE_NOT_FOUND = 'PLACE_NOT_FOUND',
  PLACE_SLUG_CONFLICT = 'PLACE_SLUG_CONFLICT',
  PROVINCE_NOT_FOUND = 'PROVINCE_NOT_FOUND',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
}
